services:
  api:
    container_name: php-api
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - api-volume:/app/database
volumes:
  api-volume: